// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWgBCGJ6JUDLZzj2U0Tw5cgXQ7c_Amj1M',
    appId: '1:963155328852:web:0fd211cecf65c4103b12c1',
    messagingSenderId: '963155328852',
    projectId: 'getx-938c4',
    authDomain: 'getx-938c4.firebaseapp.com',
    storageBucket: 'getx-938c4.appspot.com',
    measurementId: 'G-8YP8Y3M6FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASvdZ47bCdM5E_WwqFBfefXy5xPTHHoN4',
    appId: '1:963155328852:android:05a2ae124c48c79a3b12c1',
    messagingSenderId: '963155328852',
    projectId: 'getx-938c4',
    storageBucket: 'getx-938c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIjieAcBHz0cX2TsWuopqYQx4nCMbiBEA',
    appId: '1:963155328852:ios:88316e790ecc6fec3b12c1',
    messagingSenderId: '963155328852',
    projectId: 'getx-938c4',
    storageBucket: 'getx-938c4.appspot.com',
    iosClientId: '963155328852-6ilstjad2kdmu0fatnefbvtvr3kkibtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.getx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIjieAcBHz0cX2TsWuopqYQx4nCMbiBEA',
    appId: '1:963155328852:ios:88316e790ecc6fec3b12c1',
    messagingSenderId: '963155328852',
    projectId: 'getx-938c4',
    storageBucket: 'getx-938c4.appspot.com',
    iosClientId: '963155328852-6ilstjad2kdmu0fatnefbvtvr3kkibtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.getx',
  );
}
